### ISSUE TITLE
Open the query result in the browser, the same way pom.xml file can be

### ISSUE THREAD

**Issue by flauberjp** [Vove7/retrofit-rest-client#10]
Today behavior is this when you perform a query where the result is big, like a text in json format with more than 15 MB: a kind of progress bar is shown for the user while the file is being downloaded, in the end the file path is show for the user so he can take it, and in the same time the file is opened.

Message showing the end of the operation:
![image](https://user-images.githubusercontent.com/13665323/78192393-70628f80-744e-11ea-8aff-b0a8c9f5dd72.png)

The downloaded file is opened automatically, but IntelliJ complains about its size, so to open a big file like that is not feasible, see the messaged in red line.
![image](https://user-images.githubusercontent.com/13665323/78192489-a4d64b80-744e-11ea-9852-efeb154338b6.png)

My suggestion of improvement is to not open the file after the download, but to allow the user to click on the file path and open it on a browser. Today this operation is allowed when you in a Maven project open its pom.xml move the mouse cursor to the top right of the screen when a dialog shows up with options of the browser where the current file (pom.xml) is going to be opened if the user click on any of them, see the image.
![image](https://user-images.githubusercontent.com/13665323/78192719-11e9e100-744f-11ea-8b1b-073fc75fab84.png)

In the end pom.xml is opened, in the example below it was opened in Chrome web browser, which automatically rendered it in the correct way:
![image](https://user-images.githubusercontent.com/13665323/78192936-9d637200-744f-11ea-964d-38616de6322b.png)

**Comment by Krosxx** [comment]
https://github.com/Vove7/retrofit-rest-client#chunked-file-support

https://github.com/Vove7/retrofit-rest-client/releases/tag/2.2.4

**Comment by flauberjp** [comment]
I am unable to test it by now... 
Two possible reasons:
1) I updated my IntelliJ version to 2020.1, and it looks like to update the plug-in manually does not work. Would you know where the plug-in is now, so I can replace it manually like we are able in previous version?
2) Jetbrains need to approval newest version 2.2.4 yet, see the evidence below: 
![image](https://user-images.githubusercontent.com/13665323/79058708-b1755380-7c47-11ea-8c30-38bc1847aeb4.png)

**Comment by Krosxx** [comment]
https://github.com/Vove7/retrofit-rest-client/releases/tag/2.2.4

here can download lastest plug-in file.
