### ISSUE TITLE
不能支持https协议

### ISSUE THREAD

**Issue by lalinking** [Vove7/retrofit-rest-client#11]
请求https协议的时候提示传输错误，应该是证书导致的。可以改成信任所有ssl证书吗？

**Comment by Krosxx** [comment]
链接可以提供下吗，我方便测试

**Comment by traarttra** [comment]
Hey. I am getting an error while sending the request - # Error: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake. Do you know what the problem might be?

**Comment by skeerthikumar** [comment]
Even I am facing similar issue when using over https .

`# Error: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

Is there a way to specify Certificates / bypass this similar to what has been mentioned here ?

https://youtrack.jetbrains.com/issue/IDEA-248449?_ga=2.173995809.32949223.1616517359-423727728.1597747341

**Comment by Krosxx** [comment]
@skeerthikumar Which version are you using now?  If not 2.2.5, please try this https://github.com/Vove7/retrofit-rest-client/releases/tag/2.2.5

**Comment by skeerthikumar** [comment]
@Vove7 Thanks. I was updated the latest version by direct download that you shared. It works.
