### ISSUE TITLE
Merging code from refactored code

### ISSUE THREAD

**Issue by prog110** [Vove7/retrofit-rest-client#12]
Hi,

I did not realise that you created a clone of the original repo & published a newer version of the plugin. Few days back I took the original repo & refactored the code significantly to remove the deprecated APIs & also to ensure that the keyboard shortcuts work

I submitted a pull request to the original plugin [here](https://github.com/danblack/idea-rest-client/pull/5)

Is it possible for you to pull changes from there into this?

Even I am looking for fixing the plugin to behave similar to the enterprise one as making REST calls is extremely useful once we couple it with Intellij

Please let me know if I can be of some help in this process

**Comment by prog110** [comment]
My cloned & modified repo

https://github.com/thekalinga/idea-rest-client

**Comment by Krosxx** [comment]
Thanks. I've seen that there are too many changes in this commit, and my repo has changed a lot of source code. I'm afraid I don't have much time to deal with it.

**Comment by prog110** [comment]
Sure. I will hold off then

Thanks
