### ISSUE TITLE
在新版本上不能用了

### ISSUE THREAD

**Issue by wanghhao** [Vove7/retrofit-rest-client#15]

**Comment by Krosxx** [comment]
用在IDEA吗？ IDEA自带 `http client` 也挺好用的  
后面有空适配下新版IDEA

**Comment by Krosxx** [comment]
已适配，商店中正在审核
可先下载本地安装：https://github.com/Vove7/retrofit-rest-client/raw/main/Retrofit%20Rest%20Client-2.3.0.zip
