### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by super1117** [Vove7/retrofit-rest-client#16]
# Error: class com.google.gson.JsonPrimitive cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonPrimitive and com.google.gson.JsonObject are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @481a15ff)

**Comment by Krosxx** [comment]
插件已更新，插件商店正在审核  
现可直接下载本地安装  https://github.com/Vove7/retrofit-rest-client/raw/main/Retrofit%20Rest%20Client-2.3.0.zip
