### ISSUE TITLE
没有使用指南吗，，

### ISSUE THREAD

**Issue by jp1017** [Vove7/retrofit-rest-client#3]
rest文件，发现是后缀为rest的文件，

base_url怎么设置的

怎么运行呢 :smiling_imp:

**Comment by Krosxx** [comment]
README 有说明 https://github.com/Vove7/retrofit-rest-client#set-env-params

代码里没有自动生成`rest_env.json`文件，可以手动创建  
目录: `{projectDir}/.idea/rest-client/rest_env.json`

参考此图![](https://raw.githubusercontent.com/Vove7/retrofit-rest-client/master/pic/GIF.gif)

**Comment by liuzeze** [comment]
![image](https://user-images.githubusercontent.com/16509444/69510345-9bf0dd00-0f77-11ea-900b-75f62f73bb7a.png)
 引用不到p配置文件里的参数  点击绿色运行按钮  弹不出环境选择的框

**Comment by Krosxx** [comment]
抱歉，配置目录变更了：`{projectDir}/.idea/rest-client/rest_env.json`

**Comment by liuzeze** [comment]
这些路径支持自行配置吗

**Comment by Krosxx** [comment]
这个目前不可以， 新思路是优先当前rest文件目录下的配置，欢迎PR😄

**Comment by liuzeze** [comment]
支持两个接口连续请求吗? 第二个接口的请求参数需要第一个接口的响应数据,https://mp.weixin.qq.com/s/EbRR-ugfDAdlZXnvCOpm3Q 这个文章有说到

**Comment by Krosxx** [comment]
这个不支持的
