### ISSUE TITLE
自动添加一些默认header信息

### ISSUE THREAD

**Issue by ljg-7f** [Vove7/retrofit-rest-client#5]
一个APP中的接口往往都会携带一些共同的header信息，如：token信息。能在reset_env.json中配置默认的header信息吗？

**Comment by Krosxx** [comment]
很好的建议，后面支持

**Comment by Krosxx** [comment]
Markplace 还未审核通过 可以先下载 [retrofit-rest-client.zip](https://github.com/Vove7/retrofit-rest-client/blob/master/retrofit-rest-client.zip)

https://github.com/Vove7/retrofit-rest-client#set-env-params
