### ISSUE TITLE
Download of the query result is taking forever

### ISSUE THREAD

**Issue by flauberjp** [Vove7/retrofit-rest-client#7]
I see that in v2.2.2 the behavior changed, the content of the result is being downloaded to an external file, its path has been provived, and there is an indicator of download progress using a sequence of dots.

The main problem is that it is taking forever to download the file, could it be improved?

Besides that, below are some suggestion. If any of them make sense, we could track them by creating individuals issues.

Suggestions:
1. Show part of what was already downloaded in a formated way; 
2. Keep updating the part of what was already downloaded until the file opened in editor get to a maximum size of 2,56 MB, as that is the default size of a file on Intellij;
3. Abort the download process as soon as the user change the file or start a new query; and 
4. To turn the path in a browser link, so if the user clicks on it, the browser will show the file, what is good if the user as a plugin that formats the json file content, which is my case.

**Comment by Krosxx** [comment]
Suggestions 1 and 2 has been improved, but I have no idea to solve suggestions 4 for now.

**Comment by flauberjp** [comment]
I am going to turn the suggestions in issues, so we can track them there.

Let's use this issue to resolve the bug where the download is never ending.

**Comment by flauberjp** [comment]
Hi @Vove7 , I was notified by IntelliJ that version 2.2.3 of this plugin was available. I download it and test it, now the download is happening OK, and pretty fast. Well done! I am going to close this issue as resolved.
